version: '2'

services:
  redis-primary:
    image: {{ IMAGE }}
    ports:
      - '{{ PORT }}:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD={{ PASSWORD }}
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  redis-secondary:
    image: {{ IMAGE }}
    ports:
      - '6379'
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD={{ PASSWORD }}
      - REDIS_PASSWORD={{ PASSWORD }}
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

