version: '2'

services:
  redis:
    image: {{ IMAGE }}
    environment:
      - REDIS_PASSWORD={{ PASSWORD }}
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '{{ PORT }}:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
    restart: {{ RESTART_POLICY }}


volumes:
  redis_data:
    driver: local
